name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '00 00 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: 'Update stats by Dev Metrics'
          SHOW_PROFILE_VIEWS: 'False'
          LOCALE: 'fr'
          SHOW_LOC_CHART: 'False'
          
